### ISSUE TITLE
apply legistar template to Bay Area initial set of cities

### ISSUE THREAD

**Issue by chooliu** [Data4Democracy/town-council#29]
Apply Legistar templates in `./council_crawler/templates` to the six cities that use Legistar in our initial set of cities (see [list_of_cities.csv](https://github.com/Data4Democracy/town-council/blob/master/city_metadata/list_of_cities.csv)).

* Cupertino
* Hayward
* Mountain View
* San Leandro
* San Mateo
* Sunnyvale

(`legistar_cms.py` has not been validated for all Legistar scrapers, so check .json output before submitting a pull request!)

**Comment by brucerowan** [comment]
@josephpd3 and I have decided to start on this

**Comment by chooliu** [comment]
sounds great! @andysbolton (author of `legistar_cms.py` is probably a good resource if you guys can't make heads of what's going on!)

there's also a little documentation at his PR #28 , although because of the way our setup is right now it'd be nice for us to just have separate .py files each city (rather than have separate command line scripts for each city). 

each city's `.json` output also has yet to be validated, i think.

**Comment by chooliu** [comment]
Closing due to pull request #32 (thanks @andysbolton , @brucerowan, @josephpd3 )
