### ISSUE TITLE
municipality naming scheme

### ISSUE THREAD

**Issue by chooliu** [Data4Democracy/town-council#4]
find a system uniquely identifying cities within the database (e.g., due to possible ambiguity of "city name, state" naming system)

**Comment by davidmooreppf** [comment]
I understand from our Slack chats you've already reviewed Open Civic Data on [divisions](http://docs.opencivicdata.org/en/latest/data/division.html) and [jurisdictions](http://docs.opencivicdata.org/en/latest/data/jurisdiction.html).

**Comment by chooliu** [comment]
Whoops, I originally posted this under the wrong issue, but Aaron Strauss has implemented an easy spreadsheet for lookups [(Google Docs)](https://docs.google.com/spreadsheets/d/1oY2N3l9GckFSEOUaJrJNLNcPEqk7FTsiPH8H2GCw1lM/edit#gid=0) based on Open Civic Data's divisions & jurisdictions identifiers [(OCD github)](https://github.com/opencivicdata/ocd-division-ids/tree/master/identifiers). I'd like to use these to name cities (and their associated spider names) if possible.

**Comment by chooliu** [comment]
Note: skippable at early development stage, & in my opinion no need to go beyond "place" resolution to specifically identify particular committees.

e.g.,
`ocd-division/country:us/state:ca/place:east_palo_alto`

**Comment by bstarling** [comment]
Need to document this somewhere in the docs/readme then we can close. 

*edit* this has already been documented, whoops :)
