### ISSUE TITLE
decide on core metadata fields for cities

### ISSUE THREAD

**Issue by chooliu** [Data4Democracy/town-council#6]

**Comment by chooliu** [comment]
Look into Open Civic Data's city id schemes (https://github.com/opencivicdata/scrapers-us-municipal).

They also have a Division Identifier tool (https://docs.google.com/spreadsheets/d/1y8ObL8p3wlovo8G629XZR3TGe-_Py5JEi9eviXd_oZM/edit#gid=0).

**Comment by bstarling** [comment]
I think we need to decide whether we come up with our own schema for storing "entities" (Municipalities, towns, cities) or we try to adopt OCD's.

More info [here](http://docs.opencivicdata.org/en/latest/proposals/0002.html) and [here](http://docs.opencivicdata.org/en/latest/proposals/0003.html). If anyone is interested in researching further. I have not read through it fully, I am not sure how this would translate to local governments.

**Comment by bstarling** [comment]
Closing, working data [here](https://github.com/Data4Democracy/town-council/blob/master/city_metadata/list_of_cities.csv)
